version: "3.8"

services:
  app:
    container_name: contacts-app
    image: contacts-app
    build:
      context: .
      target: development
    volumes:
      - .:/app/
    ports:
      - 3000:3000